config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'trainings/index'
  root to: "trainings#index"
  resources :users, only: [:show]
  resources :trainings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/parts_detaile.rb
class PartsDetaile < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: 'ベンチプレス' }, { id: 3, name: 'インクラインベンチプレス' },
    { id: 4, name: 'チェストプレス' }, { id: 5, name: 'ラットプルダウン' }, { id: 6, name: 'デッドリフト' },
    { id: 7, name: 'チンニング' }, { id: 8, name: 'スクワット' }, { id: 9, name: 'レッグプレス' }, 
    { id: 10, name: 'レッグエクステンション' }, { id: 11, name: 'サイドレイズ' }, { id: 12, name: 'ショルダープレス' }, 
    { id: 13, name: 'フロントレイズ' }, { id: 14, name: 'アームカール' }, { id: 15, name: 'その他' } 
  ]

  include ActiveHash::Associations
  has_many :trainings
end

app/models/parts_outline.rb
class PartsOutline < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '胸' }, { id: 3, name: '背中' },
    { id: 4, name: '脚' }, { id: 5, name: '肩' }, { id: 6, name: '腕' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :trainings
end

app/models/training.rb
class Training < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :parts_outline
  belongs_to :parts_detaile

  with_options presence: true do
    validates :start_time
    validates :weight, numericality: { only_integer: true, message: 'Half-width number' }
    validates :number_of_times, numericality: { only_integer: true, message: 'Half-width number' }

    with_options numericality: { other_than: 1, message: 'Select' } do
      validates :parts_outline_id
      validates :parts_detaile_id
    end
  end

  validates :text, presence: true, unless: :was_attached?
  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true

  has_many :trainings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController


  def index
    @trainings = Training.includes(:user).order('created_at DESC')
  end

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @training = Training.find(params[:id])
  end

  def edit
  end

  def update
    if @training.update(training_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    training = Training.find(params[:id])
    training.destroy
    redirect_to root_path
  end



  private

  def training_params
    params.require(:training).permit(:parts_outline_id, :parts_detaile_id, :start_time, :weight, :number_of_times, :text, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @name = @user.name
    @trainings = @user.trainings
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuscleBuddy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">

      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to "MuscleBuddy", root_path, class: :logo %>
          </div>
          <div class="nav__right">
              <%= link_to "本日のトレーニング", new_training_path, class: :nav__btn %>
              <%= link_to "Nice Rep", root_path, class: :nav__logout %>
              <%= link_to "My Rep", "/users/#{current_user.id}", class: :nav__btn %>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trainings/_form.html.erb
<%= form_with(model: training, local: true) do |f|%>
  <div class="items-detail">
    <div class="weight-bold-text">商品の詳細</div>
    <div class="form">
      <div class="weight-bold-text">
        パーツ
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:parts_outline_id, PartsOutline.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <div class="weight-bold-text">
        トレーニング内容
      </div>
      <%= f.collection_select(:parts_detaile_id, PartsDetaile.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    </div>
  </div>

  <div class="field">
    <%= f.label :start_time, "トレーニング日時" %><br />
    <%= f.date_field :start_time, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :weight, "重さ (kg)" %><br />
    <%= f.text_field :weight, class: :form__text, size: 30,  id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :number_of_times, "× Rep" %><br />
    <%= f.number_field :number_of_times, class: :form__text, id:"prototype_concept" %>
  </div>

    <div class="field">
    <%= f.label :text, "ツイート" %><br />
    <%= f.text_area :text, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "筋トレ画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/trainings/_training.html.erb
<div class="card">
  <%= link_to training.user.name+" のトレーニング", user_path(training.user_id), class: :card__user %>
    <p class="card__summary">
    <%= training.text %>
    </p>
  <div class="card__body">
    <%= link_to training.parts_outline.name, training_path(training.user_id), class: :card__title %>
    <%= link_to training.parts_detaile.name, training_path(training.user_id) %>
    <%= training.weight %><%= " kg " %><%= training.number_of_times %><%= " Reps" %>
  </div>
  <%= link_to image_tag(training.image.variant(resize: '500x500'), class: :card__img ), training_path(training.user_id)  if training.image.attached?%>
</div>

app/views/trainings/index.html.erb
<main class="main">
  <div class="inner">
    <% @trainings.each do |training| %>
    <%= render partial: "training", locals:{training: training} %>
    <% end %>
  </div>

</main>

app/views/trainings/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">今日のトレーニングを追加する</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: {training:@training} %>
    </div>
  </div>
</div>

app/views/trainings/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <%= link_to "by "+@training.user.name, user_path(@training.user_id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @training.user_id %>
        <div class="prototype__manage">
          <%= link_to "削除する", training_path(@training), class: :prototype__btn, method: :delete %>
        </div>
      <% end %>
      <div class="prototype__body">
        <%= @training.start_time %>
      </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag @training.image if @training.image.attached? %>
      </div>
      <div class="prototype__body">
        <%= @training.text %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">部位</p>
          <p class="detail__message">
            <%= @training.parts_outline.name %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">内容</p>
          <p class="detail__message">
            <%= @training.parts_detaile.name %>
          </p>
          <p class="detail__message">
            <%= @training.weight %><%= "kg × "%><%= @training.number_of_times %><%= "Reps"%>
          </p>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @name+"さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @name %></td>
          </tr>
          <tr>
            <th class="table__col1">トレーニング</th>
            <td class="table__col2">

              <%= month_calendar events: @trainings do |date, trainings| %>
                <%= date %>
                <% trainings.each do |training|%>
                  <div class="has-events">
                    <%= training.parts_outline.name %>
                  </div>
                <% end %>
              <% end %>
              
            </td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @name+"のトレーニング"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial:"trainings/training", collection:@trainings %>
      </div>
    </div>
  </div>
</div>